MOCK_BIRDS = [
    {
        "species_code": "amecro",
        "common_name": "American Crow",
        "scientific_name": "Corvus brachyrhynchos",
        "reason": "Harsh caw-like profile typical of a corvid vocalization.",
        "metadata": {
            "family": "Corvidae",
            "habitat": ["suburbs", "parks", "open woodland"],
            "diet": ["insects", "grain", "small animals", "scraps"],
            "behavior": ["loud cawing", "group foraging", "high perches"],
            "best_time_to_find": "Early morning and late afternoon",
            "seasonal_status": "Common year-round in much of North America",
            "conservation_status": "Least Concern",
            "look_for": ["large black body", "fan-shaped tail", "confident stride"],
        },
    },
    {
        "species_code": "nocar",
        "common_name": "Northern Cardinal",
        "scientific_name": "Cardinalis cardinalis",
        "reason": "Clear whistled phrases with a strong tonal structure.",
        "metadata": {
            "family": "Cardinalidae",
            "habitat": ["shrubs", "suburban yards", "woodland edge"],
            "diet": ["seeds", "berries", "insects"],
            "behavior": ["rich whistles", "pairs at feeders", "sings from cover"],
            "best_time_to_find": "Dawn song and feeder visits",
            "seasonal_status": "Common year-round in eastern and central regions",
            "conservation_status": "Least Concern",
            "look_for": ["crest", "thick orange bill", "bold reddish plumage or warm brown female tones"],
        },
    },
    {
        "species_code": "houspa",
        "common_name": "House Sparrow",
        "scientific_name": "Passer domesticus",
        "reason": "Short repeated chirps consistent with urban sparrow chatter.",
        "metadata": {
            "family": "Passeridae",
            "habitat": ["cities", "parking lots", "storefronts"],
            "diet": ["seeds", "crumbs", "small insects"],
            "behavior": ["constant chirping", "flocks near buildings", "ground hopping"],
            "best_time_to_find": "Any daytime hour around people",
            "seasonal_status": "Established introduced resident",
            "conservation_status": "Least Concern",
            "look_for": ["chunky sparrow build", "gray-brown tones", "busy flock behavior"],
        },
    },
    {
        "species_code": "barswa",
        "common_name": "Barn Swallow",
        "scientific_name": "Hirundo rustica",
        "reason": "Fast twittering bursts with light buzzy elements.",
        "metadata": {
            "family": "Hirundinidae",
            "habitat": ["open fields", "barns", "shorelines"],
            "diet": ["flying insects"],
            "behavior": ["aerial feeding", "wire perching", "twittering chatter"],
            "best_time_to_find": "Warm daylight hours with insect activity",
            "seasonal_status": "Mostly spring and summer breeder",
            "conservation_status": "Least Concern",
            "look_for": ["deep forked tail", "pointed wings", "swooping flight"],
        },
    },
]
